
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/Simplify.Project.API" # api project
    reviewers: 
      - "iamquoz"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
      directory: "/src/Simplify.Project.Front" # api project
      reviewers: 
        - "iamquoz"
      schedule:
        interval: "weekly"
